### ISSUE TITLE
Support for multizone

### ISSUE THREAD

**Issue by mturner7415** [peteS-UK/sonyavr#11]
Thanks for the plugin. Have it working well on my main zone for the STR-ZA1100ES.  Any idea on how to add multizone support?  I had another HACS plugin that worked, albeit intermittently, that has now been removed from Github.  Appreciate any guidance.

The solution before was to create a single entity (the AVR) and then entities for each of the Zones / DACS.  I'm too much of a novice to understand how to modify the plugin accordingly, however.

**Comment by peteS-UK** [comment]
Hmm.  Not sure really.  The problem with anything with these AVRs is that there's no API - I just have to look at the debug produced when you do something and try and guess how it works....  Do you still have that old plugin locally perhaps - would be interesting to see what they've done if possible.

My older AVR just seems to have a zone button and power which then sends the commands to zone 2 until your press zone+power again.  Is that how yours works with the normal remote - having seperate entities sounds like it's rather more advanced.

**Comment by mturner7415** [comment]
attached the info for the old plugin here in  zip file.

I believe my Sony works similar to the way you mentioned, but perhaps not exactly.  There are designated power buttons for each zone, though there are also designated zone selection buttons (see photo link [here](https://m.media-amazon.com/images/I/611oSgRDJnL._AC_SL1500_.jpg)).

[sony_cisip2.zip](https://github.com/user-attachments/files/18268249/sony_cisip2.zip)

**Comment by peteS-UK** [comment]
Thanks for this.  God, if only all the AVRs had that....  It's using a properly defined JSON protocol called cisip2 for the interface, which looks really straight forwards.  Sadly, I think that's only available for more recent AVRs like yours - else I'd try and update this one :-)  It's odd that it's been removed as it's a well structured integration which someone who knew home assistant integrations well has spent a lot of effort doing.  They started the process of submitting it to HACS by the look of it but then just stopped.  Maybe they got rid of the AVR....

Having said all that, sadly this doesn't help.  As you say, the integration creates a seperate entity for each zone - basically the cisip API has 3 independent media players, but the direct commands I'm using don't work like that sadly.  I've never reall tried to see what happens with the zone setup on mine since I don't use it so I'll try and take a look.

**Comment by mturner7415** [comment]
Thanks for taking a look at it so quickly.

The strange thing about that particular plugin is how unreliable it was
compared to the one you wrote. HA required restart once a day to get it
functioning properly. I never really took the time to debug it to fully
understand what was going on. I also switched my setup from a RPi 3 to a
NUC running a VM so never really isolated any issues.

Thanks again for writing this integration. I might take a look at the CISIP
plugin again and see if there’s anything I can do.

**Comment by peteS-UK** [comment]
In theory, that one should be more reliable since it's using a proper API.  The code looked well structured, but it is doing it async processing using asyncio rather than using the HA specific equivalents.  It shouldn't cause problems, but if it was crashing, that might be a good place to start.  So, in the library, it's creating the listener task.  I'd move the creation of the task to __init__.py and then use self._hass.async_create_background_task to create it.  The way it does queue management though suggest that whoever wrote it knows python and asyncio pretty well.

 I guess the real place to start would be just to run it for a bit and see if it gave anything in the logs.

**Comment by mturner7415** [comment]
Thanks for the hints.  I updated HA from previous version (think I was
running early 2024 version) and apparently broke part of the integration as
now it throws a traceback upon setup.  Error below if you're interested but
I'm going to do some more investigating over the weekend.

Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: December 30, 2024 at 5:44:26 PM (1 occurrences)
Last logged: December 30, 2024 at 5:44:26 PM

Error setting up entry Sony STR-ZA1100ES for sony_cisip2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640,
in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sony_cisip2/__init__.py", line 176, in
async_setup_entry
    device_registry = hass.helpers.device_registry.async_get(hass)
TypeError: async_get() takes 1 positional argument but 2 were given

**Comment by peteS-UK** [comment]
Hmmm - that's odd - looks fine to me at a quick glance....  I do something similar in squeezebox integration

`
from homeassistant.helpers import device_registry as dr
....
    device_registry = dr.async_get(hass)
    device = device_registry.async_get_or_create(
        config_entry_id=entry.entry_id,
        identifiers={(DOMAIN, lms.uuid)},
        name=lms.name,
        manufacturer=MANUFACTURER,
        model=SERVER_MODEL,
        sw_version=version,
        entry_type=DeviceEntryType.SERVICE,
        connections=mac_connect,
    )
`

That's from 

https://github.com/home-assistant/core/blob/dev/homeassistant/components/squeezebox/__init__.py

**Comment by peteS-UK** [comment]
I tried installing the integration, but the device creation is after discovery, so since I can't add the device I don't get as far as the error.

**Comment by gonzonia** [comment]
> Thanks again for writing this integration. I might take a look at the CISIP
> plugin again and see if there’s anything I can do.
> […](#)


I know this is a little stale, but I've taken the old CISIP integration you posted and made one that's working. (Thanks Gemini and ChatGPT!). It's far from perfect, I tried to ask Zimmra (the original developer) for permission or to find out why he pulled it, but they didn't respond. If you want to give it a try, let me know. Right now I've got the repository private but I'll happily open it up if there's interest. I could really use some help cleaning it up and making it work better if anyone is willing.
